import React from "react";
import { Platform, SafeAreaView, StatusBar as RNStatusBar, StyleSheet, Switch, Text, TouchableOpacity, useWindowDimensions, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { StatusBar } from "expo-status-bar";

const topContentPadding = Platform.OS === "android" ? (RNStatusBar.currentHeight ?? 0) + 8 : 10;
const bottomTabs = [
  { label: "Home", icon: "home-outline", route: "JobPortalHome" }, { label: "Jobs", icon: "briefcase-outline", route: "JobPortalJobs" }, { label: "Applications", icon: "document-text-outline", route: "JobPortalApplications" }, { label: "Messages", icon: "chatbox-outline", route: "JobPortalMessages" }, { label: "Profile", icon: "person", route: "JobPortalProfile" },
];
const Toggle = ({ value }) => <Switch value={value} disabled trackColor={{ false: "#D9D9E6", true: "#6A47F2" }} thumbColor="#FFFFFF" />;
const JobPortalPrivacySettingsScreen = ({ navigation }) => { const { width } = useWindowDimensions(); const contentWidth = Math.min(width - 28, 410); return <SafeAreaView style={styles.container}><StatusBar style="dark" /><View style={[styles.content, { width: contentWidth, paddingTop: topContentPadding }]}><View style={styles.card}>
  <View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={23} color="#4F5061" /></TouchableOpacity><Text style={styles.headerTitle}>Privacy Settings</Text><View style={{ width: 23 }} /></View>
  <Text style={styles.groupTitle}>Profile Visibility</Text><View style={styles.group}><Row label="Profile Visibility" right="Anyone" /><Row label="Show Email Address" toggle={false} /><Row label="Show Mobile Number" toggle /><Row label="Show Location" right="Only Recruiters" arrow /></View>
  <Text style={styles.groupTitle}>Activity Privacy</Text><View style={styles.group}><Row label="Show My Activity" toggle /><Row label="Allow Messages from Recruiters" toggle /></View>
  <Text style={styles.groupTitle}>Data & Personalization</Text><View style={styles.group}><Row label="Personalized Job Recommendations" toggle /><Row label="Allow Data Collection" toggle={false} /></View>
  </View><View style={styles.bottomNav}>{bottomTabs.map((tab) => { const active = tab.label === "Profile"; return <TouchableOpacity key={tab.label} style={styles.navItem} onPress={() => navigation.navigate(tab.route)}><Ionicons name={tab.icon} size={22} color={active ? "#5B35ED" : "#9A9BA9"} /><Text style={[styles.navText, active && styles.navTextActive]}>{tab.label}</Text></TouchableOpacity>; })}</View></View></SafeAreaView>; };
const Row = ({ label, right, arrow, toggle }) => <View style={styles.row}><Text style={styles.rowText}>{label}</Text>{right ? <Text style={styles.rightText}>{right}</Text> : null}{arrow ? <Ionicons name="chevron-forward" size={17} color="#5B35ED" /> : null}{toggle !== undefined ? <Toggle value={toggle} /> : null}</View>;
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#FAFAFE", alignItems: "center" }, content: { flex: 1, justifyContent: "space-between" }, card: { flex: 1, backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1.2, borderColor: "#EFEFF5", paddingHorizontal: 18, paddingTop: 15 }, header: { height: 34, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: "#1A1B2D", fontSize: 16, fontWeight: "900" }, groupTitle: { color: "#303244", fontSize: 13.5, fontWeight: "900", marginTop: 20, marginBottom: 10 }, group: { borderRadius: 9, borderWidth: 1.2, borderColor: "#EFEFF5", overflow: "hidden" }, row: { height: 48, flexDirection: "row", alignItems: "center", paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: "#EFEFF5" }, rowText: { flex: 1, color: "#303244", fontSize: 12.5, fontWeight: "900" }, rightText: { color: "#5B35ED", fontSize: 12.5, fontWeight: "900" }, bottomNav: { height: 67, borderTopWidth: 1, borderTopColor: "#EFEFF5", flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF" }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 }, navText: { color: "#8F90A0", fontSize: 10.5, fontWeight: "800" }, navTextActive: { color: "#5B35ED", fontWeight: "900" } });
export default JobPortalPrivacySettingsScreen;
