import React from "react";
import { Platform, SafeAreaView, StatusBar as RNStatusBar, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { StatusBar } from "expo-status-bar";
const topContentPadding = Platform.OS === "android" ? (RNStatusBar.currentHeight ?? 0) + 8 : 10;
const bottomTabs = [{ label: "Home", icon: "home-outline", route: "JobPortalHome" }, { label: "Jobs", icon: "briefcase-outline", route: "JobPortalJobs" }, { label: "Applications", icon: "document-text-outline", route: "JobPortalApplications" }, { label: "Messages", icon: "chatbox-outline", route: "JobPortalMessages" }, { label: "Profile", icon: "person", route: "JobPortalProfile" }];
const JobPortalJobPreferencesScreen = ({ navigation }) => { const { width } = useWindowDimensions(); const contentWidth = Math.min(width - 28, 410); return <SafeAreaView style={styles.container}><StatusBar style="dark" /><View style={[styles.content, { width: contentWidth, paddingTop: topContentPadding }]}><View style={styles.card}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={23} color="#4F5061" /></TouchableOpacity><Text style={styles.headerTitle}>Job Preferences</Text><View style={{ width: 23 }} /></View>
<Text style={styles.label}>Job Roles</Text><View style={styles.chipsRow}><Chip active text="React Native Developer  ×" /><Chip active text="UI/UX Designer  ×" /><TouchableOpacity style={styles.plusChip}><Ionicons name="add" size={17} color="#5B35ED" /></TouchableOpacity></View>
<Text style={styles.label}>Experience Level</Text><View style={styles.selectBox}><Text style={styles.selectText}>2 - 5 Years</Text><Ionicons name="chevron-down" size={18} color="#777987" /></View>
<Text style={styles.label}>Employment Type</Text><View style={styles.chipsRow}><Chip active text="Full Time" /><Chip text="Part Time" /><Chip text="Contract" /><Chip text="Internship" /></View>
<Text style={styles.label}>Preferred Location</Text><View style={styles.selectBox}><Text style={styles.selectText}>Ahmedabad, Gujarat</Text><Ionicons name="chevron-forward" size={18} color="#777987" /></View>
<Text style={styles.label}>Remote Preference</Text><View style={styles.chipsRow}><Chip active text="Remote" /><Chip text="On-site" /><Chip text="Hybrid" /></View>
<Text style={styles.label}>Expected Salary (Annual)</Text><View style={styles.salaryRow}><Text style={styles.salaryText}>₹ 4,00,000</Text><Text style={styles.salaryText}>₹ 8,00,000</Text><Text style={styles.salaryText}>Brd</Text></View><View style={styles.slider}><View style={styles.sliderFill} /><View style={[styles.knob, { left: "22%" }]} /><View style={[styles.knob, { left: "82%" }]} /></View>
<TouchableOpacity activeOpacity={0.9} style={styles.buttonWrap}><LinearGradient colors={["#673BF2", "#4B2BE7"]} style={styles.button}><Text style={styles.buttonText}>Save Preferences</Text></LinearGradient></TouchableOpacity></View><View style={styles.bottomNav}>{bottomTabs.map((tab) => { const active = tab.label === "Profile"; return <TouchableOpacity key={tab.label} style={styles.navItem} onPress={() => navigation.navigate(tab.route)}><Ionicons name={tab.icon} size={22} color={active ? "#5B35ED" : "#9A9BA9"} /><Text style={[styles.navText, active && styles.navTextActive]}>{tab.label}</Text></TouchableOpacity>; })}</View></View></SafeAreaView>; };
const Chip = ({ text, active }) => <View style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{text}</Text></View>;
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#FAFAFE", alignItems: "center" }, content: { flex: 1, justifyContent: "space-between" }, card: { flex: 1, backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1.2, borderColor: "#EFEFF5", paddingHorizontal: 18, paddingTop: 15 }, header: { height: 34, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: "#1A1B2D", fontSize: 16, fontWeight: "900" }, label: { color: "#303244", fontSize: 12.5, fontWeight: "900", marginTop: 16, marginBottom: 8 }, chipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { height: 31, borderRadius: 6, borderWidth: 1.2, borderColor: "#E7E7F0", paddingHorizontal: 12, alignItems: "center", justifyContent: "center" }, chipActive: { backgroundColor: "#F0ECFF", borderColor: "#E0D8FF" }, chipText: { color: "#303244", fontSize: 11.5, fontWeight: "900" }, chipTextActive: { color: "#5B35ED" }, plusChip: { width: 31, height: 31, borderRadius: 16, backgroundColor: "#F0ECFF", alignItems: "center", justifyContent: "center" }, selectBox: { height: 39, borderRadius: 6, borderWidth: 1.2, borderColor: "#E7E7F0", flexDirection: "row", alignItems: "center", paddingHorizontal: 12 }, selectText: { flex: 1, color: "#303244", fontSize: 12.5, fontWeight: "900" }, salaryRow: { flexDirection: "row", justifyContent: "space-between" }, salaryText: { color: "#303244", fontSize: 12, fontWeight: "900" }, slider: { height: 5, borderRadius: 3, backgroundColor: "#E6E2F9", marginTop: 12 }, sliderFill: { width: "64%", marginLeft: "22%", height: 5, backgroundColor: "#5B35ED" }, knob: { position: "absolute", top: -5, width: 15, height: 15, borderRadius: 8, backgroundColor: "#FFFFFF", borderWidth: 4, borderColor: "#5B35ED" }, buttonWrap: { marginTop: 27 }, button: { height: 43, borderRadius: 6, alignItems: "center", justifyContent: "center" }, buttonText: { color: "#FFFFFF", fontSize: 13.5, fontWeight: "900" }, bottomNav: { height: 67, borderTopWidth: 1, borderTopColor: "#EFEFF5", flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF" }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 }, navText: { color: "#8F90A0", fontSize: 10.5, fontWeight: "800" }, navTextActive: { color: "#5B35ED", fontWeight: "900" } });
export default JobPortalJobPreferencesScreen;
